[project]
name = "bulk-email-builder"
version = "0.1.0"
description = "Tool to bulk configure emails"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mysql-connector-python==9.4.0",
]
